stages:
  - lint
  - build
  - test
  - publish

.container:
  image: runner.hideout:5000/meld/rs-meld:latest
  stage: build
  interruptible: true
  allow_failure: false
  timeout: 10m

Lint:
  extends:
    - .container
  stage: lint
  script:
    - test -d ./$CUR_PROJ/src || exit
    - cargo fmt

Build:
  needs: ["Lint"]
  extends:
    - .container
  stage: build
  script:
    - cargo build -v --release
  artifacts:
    paths:
    - target/release/

Test:
  needs: ["Build"]
  extends:
    - .container
  stage: test
  script:
    - cargo test 

Publish:
  needs: ["Test"]
  extends:
    - .container
  stage: publish
  only:
    variables: [ $publish == "true" ]
  variables:
    TOKEN: "$CRATES_TOKEN"
  script:
    - cargo publish --dry-run
    - cargo login $TOKEN
    - cargo package
    - cargo publish
