stages:
  - lint
  - build
  - test
  - publish

.container:
  image: runner.hideout:5000/meld/rs-meld:latest
  stage: build
  interruptible: true
  allow_failure: false
  timeout: 10m

list-rs:
  extends:
    - .container
  stage: lint
  script:
    - test -d ./$CUR_PROJ/src || exit
    - cargo fmt --check

build-rs:
  needs: ["lint-rs"]
  extends:
    - .container
  stage: build
  script:
    - cargo build -v --release
  artifacts:
    paths:
    - target/release/

test-rs-function:
  needs: ["build-rs"]
  extends:
    - .container
  stage: test
  script:
    - cargo test 