stages:
  - lint
  - build
  - test
  - publish

.container:
  image: registry.parker.systems/meld/meld-rust:latest
  stage: build
  interruptible: true
  allow_failure: false
  timeout: 10m
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

lint-rs:
  extends:
    - .container
  stage: lint
  script:
    - test -d ./$CUR_PROJ/src || exit
    - cargo fmt --check

build-rs:
  needs: ["lint-rs"]
  extends:
    - .container
  stage: build
  script:
    - cargo build -v --release
  artifacts:
    paths:
    - target/release/

test-rs-function:
  needs: ["build-rs"]
  extends:
    - .container
  stage: test
  script:
    - cargo test 

test-meld-suite:
  needs: ["build-rs"]
  stage: test
  extends:
    - .container
  script:
    - git submodule update --init
    - cd meld-test-suite
    - CLIENTBIN=$(pwd)/../target/release/meld ./run_tests.sh
